on:
  rss:
    url:
      - https://weekly.tw93.fun/rss.xml
      - https://jiashejianyan.com/rss/
      - https://rsshub.app/zhubai/shyrz
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{apikey}}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "folder":"邮箱订阅"
            }
